--插入菜单

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10', '系统管理', null, '0', '00', '01', CURRENT_TIMESTAMP(), null, null, null);
insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-10', '系统菜单管理', '/sysMenu/initQuery', '10', '01', '01', CURRENT_TIMESTAMP(), null, null, '01');
insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-12', '系统用户管理', '/admin/initQuery', '10', '01', '01', CURRENT_TIMESTAMP(), null, null, '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-13', '系统角色管理', '/sysRole/initQuery', '10', '01', '01', CURRENT_TIMESTAMP(), null, null, '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-10-10', '添加', '/sysMenu/initAdd', '10-10', '04', '01', CURRENT_TIMESTAMP(), 'icon-add', null, '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-10-11', '修改', '/sysMenu/initUpdate', '10-10', '04', '01', CURRENT_TIMESTAMP(), 'icon-edit', '01', '01');
insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-10-12', '删除', '/sysMenu/delete', '10-10', '04', '01', CURRENT_TIMESTAMP(), 'icon-remove', '02', '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-10-13', '查看', '/sysMenu/initQueryDetail', '10-10', '04', '01', CURRENT_TIMESTAMP(), 'icon-search', '01', '01');



insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-12-10', '添加', '/admin/initAdd', '10-12', '04', '01', CURRENT_TIMESTAMP(), 'icon-add', null, '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-12-11', '修改', '/admin/initUpdate', '10-12', '04', '01', CURRENT_TIMESTAMP(), 'icon-edit', '01', '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-12-12', '删除', '/admin/delete', '10-12', '04', '01', CURRENT_TIMESTAMP(), 'icon-remove', '02', '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-12-13', '查看', '/admin/initQueryDetail', '10-12', '04', '01', CURRENT_TIMESTAMP(), 'icon-search', '01', '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-12-14', '设置角色', '/admin/initSetRole', '10-12', '04', '01', CURRENT_TIMESTAMP(), 'icon-edit', '01', '01');


insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-13-10', '添加', '/sysRole/initAdd', '10-13', '04', '01', CURRENT_TIMESTAMP(), 'icon-add', null, '01');
insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-13-11', '修改', '/sysRole/initUpdate', '10-13', '04', '01', CURRENT_TIMESTAMP(), 'icon-edit', '01', '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-13-12', '删除', '/sysRole/delete', '10-13', '04', '01', CURRENT_TIMESTAMP(), 'icon-remove', '02', '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-13-13', '查看', '/sysRole /initQueryDetail', '10-13', '04', '01', CURRENT_TIMESTAMP(), 'icon-search', '01', '01');

insert into TB_SYS_MENU (SYSMENUNO, SYSMENUNAME, SYSMENUURL, PARENTNO, LEVELCODE, USESTATUS, CREATETIME, SYSMENUICONCLS, SYSMENUEXECUTEJS, SYSMENUOPENSTYLE)
values ('10-13-14', '设置权限', '/sysRole /initSetAuthority', '10-13', '04', '01', CURRENT_TIMESTAMP(), 'icon-edit', '01', '01');

